# Generated by Django 4.0.4 on 2022-06-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NoteTakingApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
