# Generated by Django 4.0.5 on 2022-06-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='content',
            field=models.TextField(),
        ),
    ]
